### ISSUE TITLE
Use of undefined constant BEYONIC_CLIENT_VERSION 

### ISSUE THREAD

**Issue by paulobunga** [beyonic/beyonic-php#6]
Am using composer autoload, Codeigniter 3.1.4

`public function request_funds()
    {
        $collection_request = Beyonic_Collection_Request::create(array(
            "phonenumber" => "+80000000001",
            "amount" => "100.2",
            "currency" => "BXC",
            "metadata" => array("my_id"=>"123ASDAsd123"),
            "send_instructions" => True
        ));

        echo json_encode($collection_request);
    }`

And the URL : http://localhost:8090/index.php/test_beyonic/request_funds

I am not quite sure what is causing this but I can't fix it and need some help

**Comment by nickhargreaves** [comment]
Hi are you using the latest source code from the master branch?

**Comment by paulobunga** [comment]
I used a version I installed from Composer.

**Comment by emugabi** [comment]
Hey @paulobunga, be sure to define the Beyonic Client Version prior to any request. 
For instance, in your parent class constructor method.

```
class BaseClass {

   function __construct() {
       define("BEYONIC_CLIENT_VERSION", "0.0.4");
   }

   public function request_funds(){
      $collection_request = Beyonic_Collection_Request::create(array(
      "phonenumber" => "+80000000001",
      "amount" => "100.2",
      "currency" => "BXC",
      "metadata" => array("my_id"=>"123ASDAsd123"),
      "send_instructions" => True
     ));
}
```

**Comment by paulobunga** [comment]
Yah @emugabi, figured that out. Thanks though
